-- ======= Copyright (c) 2003-2010, Unknown Worlds Entertainment, Inc. All rights reserved. =======
--
-- lua\IMGlobals.lua
--
--    Created by:   Trevor Harris (trevor@naturalselection2.com)
--
--    Add an "IsInfested" field to the player info.
--
-- ========= For more information, visit us at http://www.unknownworlds.com =====================
